#pragma once

#include <DxLib.h>

#include "KeyConstants.h"
#include "MouseConstants.h"
#include "GamePadConstants.h"

namespace DxlibConstants
{
	// 独自の列挙体とDxlibとの対応付け
	inline static int KeyTable[(int)KeyConstants::Count]
	{
		KEY_INPUT_BACK,
		KEY_INPUT_TAB,
		KEY_INPUT_RETURN,

		KEY_INPUT_LSHIFT,
		KEY_INPUT_RSHIFT,
		KEY_INPUT_LCONTROL,
		KEY_INPUT_RCONTROL,
		KEY_INPUT_ESCAPE,
		KEY_INPUT_SPACE,
		KEY_INPUT_PGUP,
		KEY_INPUT_PGDN,
		KEY_INPUT_END,
		KEY_INPUT_HOME,
		KEY_INPUT_LEFT,
		KEY_INPUT_UP,
		KEY_INPUT_RIGHT,
		KEY_INPUT_DOWN,
		KEY_INPUT_INSERT,
		KEY_INPUT_DELETE,

		KEY_INPUT_MINUS,
		KEY_INPUT_YEN,
		KEY_INPUT_PREVTRACK,
		KEY_INPUT_PERIOD,
		KEY_INPUT_SLASH,
		KEY_INPUT_LALT,
		KEY_INPUT_RALT,
		KEY_INPUT_SEMICOLON,
		KEY_INPUT_COLON,
		KEY_INPUT_LBRACKET,
		KEY_INPUT_RBRACKET,
		KEY_INPUT_AT,
		KEY_INPUT_BACKSLASH,
		KEY_INPUT_COMMA,
		KEY_INPUT_CAPSLOCK,
		KEY_INPUT_PAUSE,

		KEY_INPUT_NUMPAD0,
		KEY_INPUT_NUMPAD1,
		KEY_INPUT_NUMPAD2,
		KEY_INPUT_NUMPAD3,
		KEY_INPUT_NUMPAD4,
		KEY_INPUT_NUMPAD5,
		KEY_INPUT_NUMPAD6,
		KEY_INPUT_NUMPAD7,
		KEY_INPUT_NUMPAD8,
		KEY_INPUT_NUMPAD9,
		KEY_INPUT_MULTIPLY,
		KEY_INPUT_ADD,
		KEY_INPUT_SUBTRACT,
		KEY_INPUT_DECIMAL,
		KEY_INPUT_DIVIDE,
		KEY_INPUT_NUMPADENTER,

		KEY_INPUT_F1,
		KEY_INPUT_F2,
		KEY_INPUT_F3,
		KEY_INPUT_F4,
		KEY_INPUT_F5,
		KEY_INPUT_F6,
		KEY_INPUT_F7,
		KEY_INPUT_F8,
		KEY_INPUT_F9,
		KEY_INPUT_F10,
		KEY_INPUT_F11,
		KEY_INPUT_F12,

		KEY_INPUT_A,
		KEY_INPUT_B,
		KEY_INPUT_C,
		KEY_INPUT_D,
		KEY_INPUT_E,
		KEY_INPUT_F,
		KEY_INPUT_G,
		KEY_INPUT_H,
		KEY_INPUT_I,
		KEY_INPUT_J,
		KEY_INPUT_K,
		KEY_INPUT_L,
		KEY_INPUT_M,
		KEY_INPUT_N,
		KEY_INPUT_O,
		KEY_INPUT_P,
		KEY_INPUT_Q,
		KEY_INPUT_R,
		KEY_INPUT_S,
		KEY_INPUT_T,
		KEY_INPUT_U,
		KEY_INPUT_V,
		KEY_INPUT_W,
		KEY_INPUT_X,
		KEY_INPUT_Y,
		KEY_INPUT_Z,

		KEY_INPUT_0,
		KEY_INPUT_1,
		KEY_INPUT_2,
		KEY_INPUT_3,
		KEY_INPUT_4,
		KEY_INPUT_5,
		KEY_INPUT_6,
		KEY_INPUT_7,
		KEY_INPUT_8,
		KEY_INPUT_9
	};

	// MouseButtonとDxLibとの対応
	inline constexpr int DxlibMouseButtonTable[static_cast<int>(MouseButton::Count)]
	{
		MOUSE_INPUT_LEFT,
		MOUSE_INPUT_RIGHT,
		MOUSE_INPUT_MIDDLE,

		MOUSE_INPUT_4,
		MOUSE_INPUT_5,
		MOUSE_INPUT_6,
		MOUSE_INPUT_7,
		MOUSE_INPUT_8
	};

	inline constexpr int DXLIB_INVALID_INPUT{ -1 };

	// GamepadButtonとXINPUT_STATE::Buttonsの添字との対応
	inline constexpr int DxlibXInputButtonTable[static_cast<int>(GamePadButton::Count)]
	{
		// フェイスボタン
		XINPUT_BUTTON_A,                 // BUTTON_SOUTH
		XINPUT_BUTTON_B,                 // BUTTON_EAST
		XINPUT_BUTTON_X,                 // BUTTON_WEST
		XINPUT_BUTTON_Y,                 // BUTTON_NORTH

		// ショルダー
		XINPUT_BUTTON_LEFT_SHOULDER,     // LEFT_SHOULDER
		XINPUT_BUTTON_RIGHT_SHOULDER,    // RIGHT_SHOULDER

		// スティック押し込み
		XINPUT_BUTTON_LEFT_THUMB,        // LEFT_STICK_PRESS
		XINPUT_BUTTON_RIGHT_THUMB,       // RIGHT_STICK_PRESS

		// 方向パッド
		XINPUT_BUTTON_DPAD_UP,           // DPAD_UP
		XINPUT_BUTTON_DPAD_DOWN,         // DPAD_DOWN
		XINPUT_BUTTON_DPAD_LEFT,         // DPAD_LEFT
		XINPUT_BUTTON_DPAD_RIGHT,        // DPAD_RIGHT

		// システムボタン
		XINPUT_BUTTON_BACK,              // SELECT
		XINPUT_BUTTON_START,             // START
		DXLIB_INVALID_INPUT              // GUIDE
	};

	using DxlibXInputAxis1DMember = unsigned char XINPUT_STATE::*;

	inline constexpr DxlibXInputAxis1DMember DxlibXInputAxis1DTable[static_cast<int>(GamePadAxis1D::Count)]
	{
		&XINPUT_STATE::LeftTrigger,
		&XINPUT_STATE::RightTrigger
	};

	struct DxlibXInputAxis2DMembers
	{
		short XINPUT_STATE::* x;
		short XINPUT_STATE::* y;
	};

	inline constexpr DxlibXInputAxis2DMembers DxlibXInputAxis2DTable[static_cast<int>(GamePadAxis2D::Count)]
	{
		{
			&XINPUT_STATE::ThumbLX,
			&XINPUT_STATE::ThumbLY
		},
		{
			&XINPUT_STATE::ThumbRX,
			&XINPUT_STATE::ThumbRY
		}
	};
}
